/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolitaireRouteImport } from './routes/solitaire'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemoryGameIdRouteImport } from './routes/memory/game/$id'

const SolitaireRoute = SolitaireRouteImport.update({
  id: '/solitaire',
  path: '/solitaire',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryGameIdRoute = MemoryGameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => MemoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/memory': typeof MemoryRouteWithChildren
  '/solitaire': typeof SolitaireRoute
  '/memory/game/$id': typeof MemoryGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/memory': typeof MemoryRouteWithChildren
  '/solitaire': typeof SolitaireRoute
  '/memory/game/$id': typeof MemoryGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/memory': typeof MemoryRouteWithChildren
  '/solitaire': typeof SolitaireRoute
  '/memory/game/$id': typeof MemoryGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/memory' | '/solitaire' | '/memory/game/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/memory' | '/solitaire' | '/memory/game/$id'
  id: '__root__' | '/' | '/auth' | '/memory' | '/solitaire' | '/memory/game/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MemoryRoute: typeof MemoryRouteWithChildren
  SolitaireRoute: typeof SolitaireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solitaire': {
      id: '/solitaire'
      path: '/solitaire'
      fullPath: '/solitaire'
      preLoaderRoute: typeof SolitaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/game/$id': {
      id: '/memory/game/$id'
      path: '/game/$id'
      fullPath: '/memory/game/$id'
      preLoaderRoute: typeof MemoryGameIdRouteImport
      parentRoute: typeof MemoryRoute
    }
  }
}

interface MemoryRouteChildren {
  MemoryGameIdRoute: typeof MemoryGameIdRoute
}

const MemoryRouteChildren: MemoryRouteChildren = {
  MemoryGameIdRoute: MemoryGameIdRoute,
}

const MemoryRouteWithChildren =
  MemoryRoute._addFileChildren(MemoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MemoryRoute: MemoryRouteWithChildren,
  SolitaireRoute: SolitaireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
